#!/usr/bin/env python3
"""Generate a SYNTHETIC ESPN-shaped league payload for offline testing.

Nothing here is real ESPN data. My own roster uses the real player names from
data/roster_2026.json so the output is recognisable, but every projection is
fabricated (week-1 projection x 17, which is not how ESPN computes a season
total). The other eleven rosters are invented outright.

Its only job is to let `tools/league_map.py --from` run somewhere that cannot
reach lm-api-reads.fantasy.espn.com -- which includes every Claude Cloud
session. Never read a conclusion about the real league off this file.

    python3 tests/make_sample_league.py > tests/sample_league.raw.json
"""

from __future__ import annotations

import json
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

ELIGIBLE = {
    "QB": [0, 7, 20, 21],
    "RB": [2, 3, 23, 7, 20, 21],
    "WR": [3, 4, 5, 23, 7, 20, 21],
    "TE": [5, 6, 23, 7, 20, 21],
    "K": [17, 20, 21],
    "D/ST": [16, 20, 21],
}
PRO_TEAM_IDS = {"PHI": 21, "SF": 25, "LAC": 24, "WSH": 28, "NYG": 19, "TB": 27,
                "CLE": 5, "PIT": 23, "DAL": 6, "DET": 8, "ARI": 22, "CHI": 3,
                "NE": 17, "NO": 18, "KC": 12}

# 1 QB, 2 RB, 2 WR, 1 TE, 1 RB/WR flex, 1 D/ST, 1 K, 6 bench -- Schobbetruppe.
LINEUP_SLOT_COUNTS = {"0": 1, "2": 2, "4": 2, "6": 1, "3": 1, "16": 1, "17": 1, "20": 6}

# Rival roster shapes, chosen so the map has something to find: a back-hoarder,
# a receiver-hoarder, a team with no kicker, and eight roughly balanced ones.
SHAPES = {
    "hoards backs": [("QB", 17.0), ("RB", 19.0), ("RB", 16.5), ("RB", 15.0),
                     ("RB", 13.5), ("RB", 12.0), ("WR", 12.5), ("WR", 9.0),
                     ("WR", 7.5), ("TE", 8.0), ("K", 8.5), ("D/ST", 6.5),
                     ("QB", 12.0), ("TE", 5.5)],
    "hoards receivers": [("QB", 18.5), ("RB", 11.0), ("RB", 8.0), ("RB", 6.5),
                         ("WR", 18.0), ("WR", 16.0), ("WR", 15.0), ("WR", 14.0),
                         ("WR", 12.5), ("TE", 9.5), ("K", 9.0), ("D/ST", 7.0),
                         ("QB", 11.5), ("TE", 6.0)],
    "no kicker": [("QB", 19.5), ("RB", 15.5), ("RB", 13.0), ("RB", 9.0),
                  ("WR", 15.5), ("WR", 13.0), ("WR", 10.5), ("TE", 11.0),
                  ("D/ST", 7.5), ("QB", 12.5), ("RB", 7.0), ("WR", 8.0),
                  ("TE", 6.5), ("D/ST", 5.0)],
    "balanced": [("QB", 18.0), ("RB", 16.0), ("RB", 13.5), ("RB", 10.0),
                 ("WR", 15.0), ("WR", 13.0), ("WR", 10.0), ("TE", 9.5),
                 ("K", 9.0), ("D/ST", 7.0), ("QB", 12.0), ("RB", 8.0),
                 ("WR", 8.5), ("TE", 6.0)],
}

WEEKS_REMAINING = 17          # the fabrication: weekly projection x this
_pid = [40000]


def entry(name: str, pos: str, week_pts: float, pro: str = "KC",
          slot: int = 20, injury: str = "ACTIVE") -> dict:
    _pid[0] += 1
    return {
        "lineupSlotId": slot,
        "playerPoolEntry": {"player": {
            "id": _pid[0],
            "fullName": name,
            "proTeamId": PRO_TEAM_IDS.get(pro, 12),
            "injuryStatus": injury,
            "eligibleSlots": list(ELIGIBLE[pos]),
            "stats": [
                {"statSourceId": 0, "scoringPeriodId": 0, "appliedTotal": 0.0},
                {"statSourceId": 1, "scoringPeriodId": 0,
                 "appliedTotal": round(week_pts * WEEKS_REMAINING, 1)},
                {"statSourceId": 1, "scoringPeriodId": 1,
                 "appliedTotal": round(week_pts, 1)},
            ],
        }},
    }


def my_team() -> dict:
    with open(os.path.join(HERE, "..", "data", "roster_2026.json"), encoding="utf-8") as fh:
        real = json.load(fh)
    slot_ids = {"QB": 0, "RB": 2, "WR": 4, "TE": 6, "FLEX": 3,
                "D/ST": 16, "K": 17, "BE": 20}
    return {
        "id": 1, "name": real["team"], "location": "", "nickname": "",
        "roster": {"entries": [
            entry(r["n"], r["p"], r["w1"], r["t"],
                  slot=slot_ids.get(r.get("slot", "BE"), 20),
                  injury="QUESTIONABLE" if r.get("q") else "ACTIVE")
            for r in real["roster"]
        ]},
    }


def build() -> dict:
    rng = random.Random(2026)
    teams = [my_team()]
    plan = ["hoards backs", "hoards receivers", "no kicker"] + ["balanced"] * 8
    for i, shape in enumerate(plan, start=2):
        jitter = 1.0 + rng.uniform(-0.10, 0.10)
        teams.append({
            "id": i, "name": f"Rival {i:02d} ({shape})",
            "location": "", "nickname": "",
            "roster": {"entries": [
                entry(f"{pos} {i:02d}-{n + 1}", pos, round(pts * jitter, 1))
                for n, (pos, pts) in enumerate(SHAPES[shape])
            ]},
        })
    return {
        "_source": "SYNTHETIC. Generated by tests/make_sample_league.py. "
                   "Not ESPN data; projections are fabricated.",
        "id": 461530087, "seasonId": 2026, "scoringPeriodId": 1,
        "settings": {
            "name": "Schobbetruppe (synthetic copy)",
            "size": 12,
            "rosterSettings": {"lineupSlotCounts": dict(LINEUP_SLOT_COUNTS)},
            "scoringSettings": {"scoringItems": [{"statId": 53, "points": 0.5}]},
        },
        "teams": teams,
    }


if __name__ == "__main__":
    json.dump(build(), sys.stdout, indent=2)
    sys.stdout.write("\n")
