#!/data/data/com.termux/files/usr/bin/bash
# Schedule the poll via Android's JobScheduler.
#
# Requires the Termux:API companion app (F-Droid) in addition to the
# termux-api package - the package is only the CLI half.
#
#   bash deploy/termux-schedule.sh            # every 3 hours
#   bash deploy/termux-schedule.sh --cancel
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNNER="$REPO/deploy/termux-poll-runner.sh"
PERIOD_MS=10800000   # 3 hours

if ! command -v termux-job-scheduler >/dev/null 2>&1; then
  echo "termux-job-scheduler not found. Install both halves:" >&2
  echo "  pkg install termux-api        # the CLI" >&2
  echo "  and the Termux:API app from F-Droid   # the permissions half" >&2
  exit 1
fi

if [[ "${1:-}" == "--cancel" ]]; then
  termux-job-scheduler --cancel-all
  echo "Cancelled all Termux scheduled jobs."
  exit 0
fi

cat > "$RUNNER" <<RUNNER_EOF
#!/data/data/com.termux/files/usr/bin/bash
# Generated by termux-schedule.sh - safe to regenerate.
cd "$REPO"
termux-wake-lock
python tools/poll_espn.py >> "$REPO/data/live/poll.log" 2>&1
termux-wake-unlock
RUNNER_EOF
chmod +x "$RUNNER"

echo "Verifying a poll succeeds before scheduling it..."
cd "$REPO"
if ! python tools/poll_espn.py; then
  echo "Poll failed. Fix that before scheduling a job that would only fail." >&2
  exit 1
fi

termux-job-scheduler \
  --script "$RUNNER" \
  --period-ms "$PERIOD_MS" \
  --persisted true \
  --network any

echo
echo "Scheduled every 3 hours (Android may defer it under Doze; that is fine here)."
echo "  termux-job-scheduler --pending      # list jobs"
echo "  bash deploy/termux-schedule.sh --cancel"
echo "  tail -f data/live/poll.log          # watch it work"
